### ISSUE TITLE
遇到过运行超时吗？怎么解决的？

### ISSUE THREAD

**Issue by xiaohai-78** [jianyuan1991/ragdemo#1]
org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://localhost:11434/api/chat": Read timed out
	at org.springframework.web.client.DefaultRestClient$DefaultRequestBodyUriSpec.createResourceAccessException(DefaultRestClient.java:573) ~[spring-web-6.1.12.jar:6.1.12]
	at org.springframework.web.client.DefaultRestClient$DefaultRequestBodyUriSpec.exchangeInternal(DefaultRestClient.java:496) ~[spring-web-6.1.12.jar:6.1.12]
	at org.springframework.web.client.DefaultRestClient$DefaultRequestBodyUriSpec.retrieve(DefaultRestClient.java:458) ~[spring-web-6.1.12.jar:6.1.12]

**Comment by star-sda** [comment]
下个小点的模型试试
